# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cd914cea1294292514c6fa30a6c89760589d5daffe5fd10712084dcd866dd71c7f12324fd820b3936101fc813900c471571e8a491688368cdb1ba3952e629fc

test:
  secret_key_base: 359d278405f5b6746157c3984d4233fd937f10bf8982735b43baa125a877d9ec9b239a8002e0bdd84889ec6376b553ba9c189a17b2a4d2edd7ff5f567836fd49

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
